- name: ansible data types
  hosts: local
  connection: local
  vars:
    DURATION: 120 # this is number
    COURSE: "DEVOOPS LEArning" # String
    IS_LIVE: true #boolean
    TOOLS: # List
    - Linux
    - shell
    - Ansible
    - git
    CONCEPTS: # Map or dictonary or object, referred like {}
      CI: jenkins
      SCRIPTING: "SHell, Ansible, Terraform, Python"
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, is live?: {{ IS_LIVE }},
      Tools are: {{ TOOLS }}, Concepts are: {{ CONCEPTS }}"