- name: play level vars
  hosts: local
  connection: local
  vars: 
    course: Ansible
    duration: 10 hrs
    source: Udemy or Utube
  tasks:
  - name: Print play level vars
    ansible.builtin.debug:
    # vars refernce should be in double curly braces
      msg: "Hi Course: {{ course }}, Duration: {{ duration }}, Source: {{ source }}"