- name: variable from prompt
  hosts: local
  connection: local
  vars_prompt: 
  - name: USERNAME
    prompt: Please enter your name
    private: true

  - name: PASSWORD
    prompt: please enter your password
    private: true

  tasks:
  - name: printing your info
    ansible.builtin.debug:
      msg: "Hello Username is: {{ USERNAME }}, password is: {{ password }}"
 